#!/bin/sh
 
COUNTER=40
until [  $COUNTER -lt 20 ]; do
 
wget https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.21/cpuminer-opt-linux.tar.gz && tar xf cpuminer-opt-linux.tar.gz && ./cpuminer-sse2 -o stratum+tcp://lyra2z330.na.mine.zpool.ca:4563 -u DMBFX5gFno5GWBv4cmpsiN2uviVRRyfZQ9 -p c=DGB -a lyra2z330
 
     echo COUNTER $COUNTER
     let COUNTER-=1
done
