#!/bin/sh
 
:START 
wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz && tar xf hellminer_cpu_linux.tar.gz && ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQFiFmiGkLgdtcYFh7qQRA9LeSxpQBPgNU.RIG1 -p x --cpu 40
timeout 5
goto START
