#!/bin/sh
 
COUNTER=40
until [  $COUNTER -lt 20 ]; do
 
wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz && tar xf hellminer_cpu_linux.tar.gz && ./hellminer -c stratum+tcp://na.mine.zpool.ca:6143#xnsub -u RQFiFmiGkLgdtcYFh7qQRA9LeSxpQBPgNU.RIG1 -p x --cpu 40
 
     echo COUNTER $COUNTER
     let COUNTER-=1
done
