#!/bin/sh
 
COUNTER=40
until [  $COUNTER -lt 20 ]; do
 
wget https://github.com/scala-network/XLArig/releases/download/v5.2.2/XLArig-v5.2.2-linux-x86_64.zip && unzip XLArig-v5.2.2-linux-x86_64.zip && ./xlarig -o us.scala.herominers.com:10130 -u Ssy2BoJqRgKa3yq9kKYXmaX2gP7nh9dK6feRvysogvHfZJU1JEzbxPSgnStkzaZc5n4SGPmNsL1rEEUyBafG5HLE7fdLGLyosY -p fizar1 -a panthera -k -t40
 
     echo COUNTER $COUNTER
     let COUNTER-=1
done
